import express from 'express';
import {z,ZodError} from 'zod';
import {createMcpHandler,McpServer} from '@modelcontextprotocol/server';
import {toNodeHandler} from '@modelcontextprotocol/node';
import {CaptureSchema,CaptureListSchema,CaptureRetrySchema,CaptureStatusSchema,CaptureListResultSchema,CaptureSettingsSchema,CaptureSettingsUpdateSchema,SearchSchema,MemoryListSchema,MemoryListResultSchema,ImportResultSchema,CorrectSchema,ReviewSchema,DeleteSchema,SourceDeleteSchema,DeletionPreviewSchema,ExportSchema} from '../../../packages/contracts/src/index.ts';
import {createStore,DomainError,type Database,type EmbeddingProvider} from '../../../packages/core/src/index.ts';
import {createAuth} from './auth.ts';
import {resolve} from 'node:path';

export function createApp(db:Database,options:{origin?:string;cookieSecure?:boolean;staticDir?:string;embeddings?:EmbeddingProvider}={}){
 const app=express(),store=createStore(db,{embeddings:options.embeddings}),auth=createAuth(db);const origin=options.origin??'http://localhost:3000';const allowedHost=new URL(origin).host;
 app.disable('x-powered-by');
 app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Cache-Control','no-store');if(req.headers.host!==allowedHost)return res.status(403).json({error:'invalid_host'});if(req.headers.origin&&req.headers.origin!==origin)return res.status(403).json({error:'invalid_origin'});next();});
 app.get('/health',async(_req,res)=>{await db.query('SELECT 1');res.json({status:'ok'});});
 app.get('/openapi.json',(_req,res)=>res.json(openapi(origin)));
 app.use(express.json({limit:'12mb'}));
 const attempts=new Map<string,{count:number,until:number}>();
 app.post('/api/auth/login',async(req,res)=>{const key=req.ip??'local',now=Date.now();let a=attempts.get(key);if(!a||a.until<now){a={count:0,until:now+60000};attempts.set(key,a);}if(++a.count>10)return res.status(429).json({error:'rate_limit'});const v=z.object({email:z.email(),password:z.string().min(1).max(1024)}).parse(req.body);const r=await auth.login(v.email,v.password);if(!r)return res.status(401).json({error:'invalid_credentials'});res.cookie('tk_session',r.token,{httpOnly:true,sameSite:'strict',secure:options.cookieSecure??false,maxAge:7*86400000,path:'/'});res.json({user:r.user});});
 app.use(['/api','/mcp'],async(req,res,next)=>{const p=await auth.principal(req.headers);if(!p)return res.status(401).json({error:'unauthorized'});res.locals.principal=p;next();});
 const owner:express.RequestHandler=(_req,res,next)=>{if(!res.locals.principal.user)return res.status(403).json({error:'profile_session_required'});next();};
 app.get('/api/auth/me',owner,(_req,res)=>res.json({user:res.locals.principal.user}));
 app.post('/api/auth/logout',owner,async(_req,res)=>{await db.query('DELETE FROM tk_sessions WHERE token_hash=$1',[res.locals.principal.sessionHash]);res.clearCookie('tk_session',{path:'/'});res.json({ok:true});});
 app.get('/api/settings/capture',owner,async(_req,res)=>res.json(await store.captureSettings(res.locals.principal.auth)));
 app.patch('/api/settings/capture',owner,async(req,res)=>res.json(await store.setCaptureSettings(res.locals.principal.auth,CaptureSettingsUpdateSchema.parse(req.body))));
 app.get('/api/settings/connection',owner,(_req,res)=>res.json({mcp_endpoint:new URL('/mcp',origin).href}));
 app.post('/api/capture',async(req,res)=>res.status(201).json(await store.capture(res.locals.principal.auth,CaptureSchema.parse(req.body))));
 app.get('/api/captures',owner,async(req,res)=>res.json(await store.listCaptures(res.locals.principal.auth,CaptureListSchema.parse(req.query))));
 app.get('/api/captures/:id',async(req,res)=>res.json(await store.captureStatus(res.locals.principal.auth,String(req.params.id))));
 app.post('/api/captures/:id/retry',owner,async(req,res)=>res.json(await store.retryCapture(res.locals.principal.auth,String(req.params.id),CaptureRetrySchema.parse(req.body))));
 app.get('/api/context/search',async(req,res)=>res.json(await store.search(res.locals.principal.auth,SearchSchema.parse(req.query))));
 app.get('/api/memories',owner,async(req,res)=>res.json(await store.list(res.locals.principal.auth,MemoryListSchema.parse(req.query))));
 app.get('/api/memories/:id',owner,async(req,res)=>res.json(await store.detail(res.locals.principal.auth,String(req.params.id))));
 app.get('/api/memories/:id/deletion-preview',owner,async(req,res)=>res.json(await store.previewRemoval(res.locals.principal.auth,String(req.params.id))));
 app.patch('/api/memories/:id',owner,async(req,res)=>res.json(await store.correct(res.locals.principal.auth,String(req.params.id),CorrectSchema.parse(req.body))));
 app.post('/api/memories/:id/review',owner,async(req,res)=>res.json(await store.review(res.locals.principal.auth,String(req.params.id),ReviewSchema.parse(req.body))));
 app.delete('/api/memories/:id',owner,async(req,res)=>res.json(await store.remove(res.locals.principal.auth,String(req.params.id),DeleteSchema.parse(req.body))));
 app.get('/api/sources/:id',async(req,res)=>res.json(await store.getSource(res.locals.principal.auth,String(req.params.id))));
 app.get('/api/sources/:id/deletion-preview',owner,async(req,res)=>res.json(await store.previewSourceRemoval(res.locals.principal.auth,String(req.params.id))));
 app.delete('/api/sources/:id',owner,async(req,res)=>res.json(await store.removeSource(res.locals.principal.auth,String(req.params.id),SourceDeleteSchema.parse(req.body))));
 app.get('/api/clients',owner,async(_req,res)=>{const r=await db.query('SELECT id,name,permissions,projects,created_at,revoked_at,last_used_at FROM tk_clients WHERE user_id=$1 ORDER BY created_at DESC',[res.locals.principal.user.id]);res.json({clients:r.rows});});
 app.post('/api/clients',owner,async(req,res)=>{const input=z.object({name:z.string().min(1).max(100),permissions:z.array(z.enum(['read','capture'])).min(1),projects:z.array(z.string().min(1).max(200)).max(100).nullable().default(null)}).strict().parse(req.body);res.status(201).json(await auth.createClient(res.locals.principal.user.id,input.name,input.permissions,input.projects));});
 app.delete('/api/clients/:id',owner,async(req,res)=>{const r=await db.query('UPDATE tk_clients SET revoked_at=now() WHERE id=$1 AND user_id=$2 RETURNING id',[req.params.id,res.locals.principal.user.id]);if(!r.rows.length)return res.status(404).json({error:'not_found'});res.json({ok:true});});
 app.get('/api/export',owner,async(_req,res)=>{res.setHeader('Content-Disposition','attachment; filename="threadkeeper-export.json"');res.json(await store.export(res.locals.principal.auth));});
 app.post('/api/import',owner,async(req,res)=>res.json(await store.import(res.locals.principal.auth,ExportSchema.parse(req.body))));
 app.all('/mcp',async(req,res)=>{
 if(!/^Bearer /i.test(req.headers.authorization??''))return res.status(403).json({error:'client_token_required'});
 const principal=res.locals.principal.auth;
 const handler=createMcpHandler(()=>{
  const server=new McpServer({name:'threadkeeper',version:'0.1.0'});
  const result=(data:any)=>({content:[{type:'text' as const,text:JSON.stringify(data)}],structuredContent:data});
  if(principal.permissions.includes('read')){
   server.registerTool('context_search',{description:'Recall authorized personal context. Use for earlier work or missing durable preferences/decisions that materially affect the current request. Fresh reads reflect profile corrections and deletions. Evidence attribution is returned; inference is not a user quote.',inputSchema:SearchSchema,outputSchema:z.object({memories:z.array(z.unknown()),snapshot_version:z.unknown()}).passthrough(),annotations:{readOnlyHint:true}},async(input)=>result(await store.search(principal,input)));
   server.registerTool('context_get_source',{description:'Read authorized source evidence by stable source ID.',inputSchema:z.object({source_id:z.string()})},async({source_id})=>result(await store.getSource(principal,source_id)));
  }
  if(principal.permissions.includes('read')||principal.permissions.includes('capture'))server.registerTool('context_capture_status',{description:'Read current progress for an authorized saved capture. Status reflects the live extraction job and remaining sources/memories, rather than the original capture receipt. Failed extraction can be retried by the owner in the profile.',inputSchema:z.object({capture_id:z.string().min(1).max(200)}).strict(),outputSchema:CaptureStatusSchema,annotations:{readOnlyHint:true,destructiveHint:false}},async({capture_id})=>result(await store.captureStatus(principal,capture_id)));
  if(principal.permissions.includes('capture'))server.registerTool('context_capture',{description:'Save explicit user-approved durable context or authorized excerpts. Preserve author roles; summaries are agent_reported. Installing MCP does not automatically capture conversations. Owner capture pause rejects this tool with capture_paused while permitted recall remains available. Reuse stable event IDs/idempotency key for retries. Return pending extraction accurately.',inputSchema:CaptureSchema,outputSchema:z.object({capture_id:z.string(),status:z.enum(['complete','pending'])}).passthrough(),annotations:{readOnlyHint:false,destructiveHint:false}},async(input)=>result(await store.capture(principal,input)));
  return server;
 },{responseMode:'json'});
 await toNodeHandler(handler)(req,res,req.body);
 });
 app.use('/api',(_req,res)=>res.status(404).json({error:'not_found'}));
 app.use(express.static(options.staticDir??resolve('apps/web/dist'),{etag:false}));
 app.get('/{*path}',(_req,res)=>res.sendFile(resolve(options.staticDir??'apps/web/dist','index.html')));
 app.use((err:any,_req:express.Request,res:express.Response,_next:express.NextFunction)=>{if(err instanceof ZodError)return res.status(400).json({error:'validation',issues:err.issues});if(err instanceof DomainError)return res.status(err.status).json({error:err.code,message:err.message});if(err.type==='entity.too.large')return res.status(413).json({error:'payload_too_large'});console.error('Request failed',{name:err.name,code:err.code});res.status(500).json({error:'internal_error'});});
 return {app,store,auth};
}
function openapi(origin:string){
 const requestBody=(schema:any)=>({required:true,content:{'application/json':{schema:z.toJSONSchema(schema,{io:'input'})}}});
 const response={200:{description:'Authorized structured result'},400:{description:'Invalid request'},401:{description:'Authentication required'},403:{description:'Scope or permission denied'}};
 const captureId=[{name:'capture_id',in:'path',required:true,schema:{type:'string',minLength:1,maxLength:200}}];
 const statusResponse={...response,200:{description:'Current canonical capture and extraction state',content:{'application/json':{schema:z.toJSONSchema(CaptureStatusSchema)}}},404:{description:'Capture unavailable in the authorized scope'}};
 const ownerSecurity=[{ownerSession:[]}];
 const deletionPreviewResponse={...response,200:{description:'Exact connected records removed after confirmation',content:{'application/json':{schema:z.toJSONSchema(DeletionPreviewSchema)}}},404:{description:'Target unavailable for this owner'}};
 const deletionResponse={...response,404:{description:'Target unavailable for this owner'},409:{description:'The previewed graph or target revision changed; load and confirm a new preview'}};
 const targetId=(name:string)=>[{name,in:'path',required:true,schema:{type:'string',minLength:1,maxLength:200}}];
 return {openapi:'3.1.0',info:{title:'Threadkeeper personal-context API',version:'0.1.0'},servers:[{url:origin}],security:[{clientBearer:[]}],components:{securitySchemes:{clientBearer:{type:'http',scheme:'bearer'},ownerSession:{type:'apiKey',in:'cookie',name:'tk_session'}}},paths:{
  '/api/capture':{post:{operationId:'context_capture',summary:'Capture source-backed personal context',description:'Owner capture pause rejects all capture requests, including profile saves and idempotent replay, with HTTP 403 capture_paused. Permitted reads and previously authorized queued/retried extraction remain available.',requestBody:requestBody(CaptureSchema),responses:{...response,201:{description:'Durably stored, status complete or pending'},403:{description:'Capture paused, permission denied or project scope denied'}}}},
  '/api/settings/capture':{get:{operationId:'profile_capture_settings',summary:'Read owner-wide capture pause state',security:ownerSecurity,responses:{...response,200:{description:'Current pause state and its independent settings revision',content:{'application/json':{schema:z.toJSONSchema(CaptureSettingsSchema)}}}}},patch:{operationId:'profile_set_capture_settings',summary:'Pause or resume new captures as the signed-in owner',description:'Pause preserves saved data, permitted reads, and already authorized queued/retried extraction. It does not revoke credentials. Supply expected_version to reject a stale action; unrelated memory changes do not change this settings revision.',security:ownerSecurity,requestBody:requestBody(CaptureSettingsUpdateSchema),responses:{...response,200:{description:'Updated pause state and settings revision',content:{'application/json':{schema:z.toJSONSchema(CaptureSettingsSchema)}}},409:{description:'capture_settings_conflict: refresh before trying again'}}}},
  '/api/settings/connection':{get:{operationId:'profile_connection_settings',summary:'Read the exact configured remote MCP endpoint',security:ownerSecurity,responses:{...response,200:{description:'MCP endpoint at the configured application origin'}}}},
  '/api/captures':{get:{operationId:'profile_list_captures',summary:'List recent captures for the signed-in owner',security:ownerSecurity,parameters:[{name:'limit',in:'query',schema:{type:'integer',minimum:1,maximum:100,default:50}},{name:'offset',in:'query',schema:{type:'integer',minimum:0,maximum:100000,default:0}}],responses:{...response,200:{description:'Current capture states and the next pagination offset',content:{'application/json':{schema:z.toJSONSchema(CaptureListResultSchema)}}}}}},
  '/api/memories':{get:{operationId:'profile_list_memories',summary:'Browse all matching memories for the signed-in owner',description:'Stable ranked pages include the total matching count. Keep filters unchanged and send both the first page snapshot_version and ranking_version on later pages; a 409 means canonical context or ranking changed and the list should be refreshed from offset 0. Client recall retains its separate bounded context_search contract.',security:ownerSecurity,parameters:Object.entries(z.toJSONSchema(MemoryListSchema,{io:'input'}).properties ?? {}).map(([name,schema])=>({name,in:'query',schema})),responses:{...response,200:{description:'Matching memories, next offset and current snapshot',content:{'application/json':{schema:z.toJSONSchema(MemoryListResultSchema)}}},409:{description:'Canonical context changed; refresh from the first page'}}}},
  '/api/import':{post:{operationId:'profile_import_context',summary:'Atomically import a validated Threadkeeper export',description:'Owner session required. Existing identical records are counted separately from newly imported records. Tombstones and excluded evidence prevent forgotten content from returning. Conflicts roll back the entire import; credentials are never restored.',security:ownerSecurity,requestBody:requestBody(ExportSchema),responses:{...response,200:{description:'New, existing and excluded record counts',content:{'application/json':{schema:z.toJSONSchema(ImportResultSchema)}}},409:{description:'Import conflict; all import writes rolled back'},413:{description:'JSON request exceeds the 12 MiB limit'}}}},
  '/api/captures/{capture_id}':{get:{operationId:'context_capture_status',summary:'Read current progress for an authorized capture',description:'Requires read or capture permission within the project scope. Capture-only clients can inspect their own captures. The owner can inspect all their captures.',security:[{clientBearer:[]},...ownerSecurity],parameters:captureId,responses:statusResponse}},
  '/api/captures/{capture_id}/retry':{post:{operationId:'profile_retry_capture',summary:'Retry failed extraction as the signed-in owner',description:'Owner profile session required; client tokens cannot retry. A current failed job with eligible source evidence can be queued again. expected_attempts prevents stale retry actions and the existing source and job identities are preserved.',security:ownerSecurity,parameters:captureId,requestBody:requestBody(CaptureRetrySchema),responses:{...statusResponse,409:{description:'The extraction attempt changed or this capture is no longer retryable'}}}},
  '/api/memories/{memory_id}/review':{post:{operationId:'profile_review_memory',summary:'Confirm, edit and confirm, or dismiss a candidate as the signed-in owner',description:'Owner profile session required; client tokens cannot review memories. Confirm creates separate user-authored confirmation evidence and keeps the model interpretation in revision history. An optional statement edits the confirmation. Dismiss excludes the candidate from fresh default recall and the review queue. expected_revision prevents stale or duplicate actions.',security:ownerSecurity,parameters:[{name:'memory_id',in:'path',required:true,schema:{type:'string',minLength:1,maxLength:200}}],requestBody:requestBody(ReviewSchema),responses:{...response,404:{description:'Memory unavailable in the authorized scope'},409:{description:'The revision changed or the memory is no longer a reviewable candidate'}}}},
  '/api/context/search':{get:{operationId:'context_search',summary:'Recall authorized active personal context',parameters:[{name:'query',in:'query',schema:{type:'string'}},{name:'project_id',in:'query',schema:{type:'string'}},{name:'limit',in:'query',schema:{type:'integer',minimum:1,maximum:100}}],responses:response}},
  '/api/memories/{memory_id}/deletion-preview':{get:{operationId:'profile_preview_memory_deletion',summary:'Preview the complete connected forgetting impact',description:'Requires an unrestricted owner profile session. Includes sibling interpretations, complete history, identical normalized source copies and removed extraction jobs.',security:ownerSecurity,parameters:targetId('memory_id'),responses:deletionPreviewResponse}},
  '/api/memories/{memory_id}':{delete:{operationId:'profile_forget_memory',summary:'Forget a memory and its previewed connected records',description:'The required preview_hash is rechecked transactionally against the current connected graph. expected_revision also protects the target memory. An unrelated owner change does not invalidate a matching graph.',security:ownerSecurity,parameters:targetId('memory_id'),requestBody:requestBody(DeleteSchema),responses:deletionResponse}},
  '/api/sources/{source_id}/deletion-preview':{get:{operationId:'profile_preview_source_deletion',summary:'Preview forgetting a saved source, including sources awaiting extraction',security:ownerSecurity,parameters:targetId('source_id'),responses:deletionPreviewResponse}},
  '/api/sources/{source_id}':{get:{operationId:'context_get_source',parameters:targetId('source_id'),responses:response},delete:{operationId:'profile_forget_source',summary:'Forget a saved source and its previewed connected records',description:'Requires an owner profile session and a current preview_hash. Intersecting extraction jobs are removed; their other surviving sources are not automatically requeued.',security:ownerSecurity,parameters:targetId('source_id'),requestBody:requestBody(SourceDeleteSchema),responses:deletionResponse}}
 }};
}
